### ISSUE TITLE
Extract slots for classes that only start at mid semester

### ISSUE THREAD

**Issue by diogotvf7** [NIAEFEUP/uporto-schedule-scrapper#108]
# The problem
The [Comunicação Profissional](https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=522327&pv_ano_lectivo=2023&pv_periodos=1&pv_periodos=3&pv_periodos=6&pv_periodos=7&pv_periodos=8&p_semana_inicio=20240225&p_semana_fim=20240330) course unit, for example, is only given to a set of classes at each time, three times per semester. 
In the current way slots are parsed, we're only checking for the occurrence of that class in the beginning of the semester, we should also check the the other time intervals in order to be able to check for other classes and slots.

**Comment by tomaspalma** [comment]
As stated in issue #110 , sigarra changed the `HTML` structure of the schedules page in a manner that now the `HTML` does not already contain the data to render, rather using javascript to make a request to an `API` and then populating the contents of the `HTML`.

Now the `API` returns all of the classes, whether or not they last all of the semester and so on, which makes this issue deprecated, since it will be solved in the refactor of the scrapper.
